---

# Bika specific NGINX configuration
bika_nginx_path: "/etc/nginx"
bika_nginx_html_root: "/usr/share/nginx/bika"
bika_nginx_sites_available: "{{ bika_nginx_path }}/sites-available"
bika_nginx_sites_enabled: "{{ bika_nginx_path }}/sites-enabled"
bika_nginx_conf: "{{ bika_nginx_path }}/nginx.conf"
bika_nginx_extra_http_options: |
  proxy_read_timeout 600s;

# VHOSTS
bika_vhosts: []
# Example:
#  - example.com
#  - test.example.com

# SSL
bika_ssl_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
bika_ssl_certificate_key: /etc/ssl/private/ssl-cert-snakeoil.key
bika_ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2"
bika_ssl_cipher_suite: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"

# https://github.com/geerlingguy/ansible-role-nginx
nginx_remove_default_vhost: true
nginx_server_names_hash_bucket_size: "256"
nginx_client_max_body_size: "1024m"
